import { lib, game, ui, get, ai, _status } from '../../../noname.js'
let lmCharacter = {//武将切换
    yj_jushou: ["old_mb_jushou"],
    zhuzhi: ["old_mb_zhuzhi"],
    guozhao: ["old_mb_guozhao"],
    chengui: ["old_mb_chengui", "old_chengui"],
    yangfu: ["yangfu", "old_yangfu"],
    wangling: ["mb_wangjingu", "old_wangling"],
    wangshuang: ["old_wangshuang"],
    wujing: ["old_wujing"],
    sp_xinpi: ["old_sp_xinpi"],
    qiaogong: ["old_qiaogong"],
    zhangzhongjing: ["zhangzhongjing", "old_xin_zhangzhongjing"],
    zhujun: ["diy_zhujun", "old_sp_zhujun"],
    weiyan: ["old_huan_weiyan", "old_pot_weiyan"],
    zhoubuyi: ["old_yj_zhoubuyi"],
    zhenji: ["old_mb_sp_zhenji"],
    mb_wangjing: ["mb_wangjing", "old_mb_wangjing"],
    jianggan: ["oldx_sp_jianggan"],
    huangzhong: ["old_sb_huangzhong"],
    gongsunzan: ["old_sb_gongsunzan"],
    sunquan: ["old_sb_sunquan", "old_v_sunquan", "old_dm_sunquan"],
    huanggai: ["old_sb_huanggai"],
    ganning: ["old_sb_ganning"],
    xiaoqiao: ["old_sb_xiaoqiao"],
    daqiao: ["old_sb_daqiao"],
    sp_zhugeliang: ["old_sb_sp_zhugeliang", "oldx_sb_sp_zhugeliang"],
    zhugeliang: ["old_wu_zhugeliang", "old_sb_zhugeliang", "oldx_sb_zhugeliang", "old_huan_zhugeliang"],
    menghuo: ["old_sb_menghuo", "lm_sb_menghuo"],
    zhurong: ["old_sb_zhurong", "old_dc_sp_zhurong"],
    guanyu: ["old_wu_guanyu", "old_sb_guanyu", "old_xia_guanyu"],
    zhaoyun: ["old_sb_zhaoyun"],
    fazheng: ["old_star_fazheng", "lm_re_fazheng"],
    xuhuang: ["old_sb_xuhuang"],
    re_yuanshao: ["old_sb_yuanshao"],
    zhangjiao: ["lm_re_zhangjiao"],
    jiaxu: ["old_sb_jiaxu"],
    huaxiong: ["old_huaxiong"],
    shenpei: ["old_shenpei"],
    majun: ["old_yj_majun"],
    nanhualaoxian: ["old_ol_nanhualaoxian"],
    dengai: ["old_ol_sb_dengai", "oldx_ol_sb_dengai", "old_dc_sb_dengai"],
    zhangliao: ["old_sb_zhangliao"],
    guojia: ["old_sb_guojia"],
    clan_xuncai: ["clan_xuncai", "oldx_clan_xuncai"],
    zhonghui: ["old_clan_zhonghui", "old_xin_zhonghui"],
    clan_hanrong: ["clan_hanrong", "old_clan_hanrong"],
    clan_hanshao: ["clan_hanshao", "old_clan_hanshao"],
    zhanghua: ["zhanghua", "old_zhanghua"],
    yuanji: ["old_yuanji"],
    tengfanglan: ["old_tengfanglan"],
    dengzhong: ["dengzhong", "old_dengzhong"],
    wangyan: ["wangyan", "old_wangyan"],
    luyusheng: ["old_ol_luyusheng", "old_mb_luyusheng"],
    hujinding: ["old_ol_hujinding"],
    feiyi: ["old_ol_feiyi"],
    ol_pengyang: ["old_ol_pengyang"],
    sunce: ["old_sp_sunce", "old_sb_sunce"],
    yufan: ["old_ol_yufan"],
    zhugejin: ["old_zhugejin", "old_sb_zhugejin"],
    xurong: ["old_xurong", "lm_xurong"],
    qianzhao: [, "old_ol_qianzhao"],
    dongzhuo: ["old_ol_sb_dongzhuo"],
    zhangchunhua: ["old_re_zhangchunhua"],
    caorui: ["old_re_caorui"],
    xushu: ["old_dc_xushu", "old_friend_xushuu"],
    yuechen: ["yuechen", "old_yuechen"],
    ruanyu: ["ruanyu", "old_ruanyu"],
    bailingyun: ["bailingyun", "old_bailingyun"],
    dc_liuli: ["dc_liuli", "old_dc_liuli"],
    miheng: ["old_yue_miheng"],
    xunyuxunyou: ["xunyuxunyou", "old_xunyuxunyou"],
    zhugejing: ["zhugejing", "old_zhugejing"],
    pangfengyi: ["pangfengyi", "old_pangfengyi"],
    wangyi: ["old_ol_wangyi"],
    lvfan: ["old_sp_lvfan"],
    huojun: ["old_tw_huojun"],
    guohuai: ["old_tw_guohuai"],
    quancong: ["oldx_quancong"],
    baoxin: ["old_tw_baoxin"],
    zhangmancheng: ["old_tw_zhangmancheng"],
    guanqiujian: ["old_tw_guanqiujian", "old_mb_sp_guanqiujian"],
    tw_niufudongxie: ["old_tw_niufudongxie"],
    tongyuan: ["old_xia_tongyuan"],
    zhugeguo: ["old_huan_zhugeguo"],
    caoang: ["old_huan_caoang"],
    jiangwei: ["old_sb_jiangwei"],
    liwei: ["old_liwei"],
    handang: ["old_sb_handang"],
    lvbu: ["old_sb_lvbu"],
    caopi: ["old_sb_caopi"],
    // xiahoudun: ["lm_sb_xiahoudun"],
    // sunxiu: ["lm_re_sunxiu"],
    // liuchen: ["lm_re_liuchen"],
    // sunliang: ["lm_sunliang"],
    // zhangxiu: ["lm_zhangxiu"],
    // yuanshu: ["lm_yl_yuanshu"],
    // liuyu: ["liuyao", "lm_liuyu"],
    // liuyao: ["zhanglu", "lm_liuyao"],
    // zhanglu: ["liuxie", "lm_zhanglu"],
    // mateng: ["lm_tw_mateng"],
    gaoshun: ["old_sb_gaoshun"],
    jikang: ["lm_jikang"],
    ol_dongzhao: ["unlock_dongzhao"],
    liuzhang: ["mx_fh_liuzhang", "old_ol_liuzhang"],
    dc_zhangren: ["old_zhangren"],
    xuelingyun: ["old_ol_xuelingyun"],
    dingfeng: ["old_star_dingfengn"],
    pot_lougui: ["old_pot_lougui"],
    liaohua: ["diy_liaohua"],
    zhangfei: ["diy_zhangfei"],
    xiahouyuan: ["old_sb_xiahouyuan"],
    chendao: ["old_pot_chendao"],
    liujinliupei: ["old_liujinliupei"],
    zhangrang: ["lm_zhangrang"],
    ol_zhaozhong: ["lm_zhaozhong"],
    lm_sunzhang: ["ps_sunzhang"],
    lm_bilan: ["ps_bilan"],
    lm_xiayun: ["ps_xiayun"],
    lm_hankui: ["ps_hankui"],
    lm_lisong: ["ps_lisong"],
    lm_duangui: ["ps_duangui"],
    lm_guosheng: ["ps_guosheng"],
    lm_gaowang: ["ps_gaowang"],
    yl_luzhi: ["old_ol_sb_yl_luzhi"],
    taishici: ["old_pot_taishici"],
    yuji: ["old_pot_yuji"],
    zhangbu: ["zhangbu", "old_zhangbu"],
    liubiao: ["old_ol_liubiao"],
    xunyu: ["old_dc_sb_xunyu"],
    wuke: ["wuke", "old_wuke"],
    kongshu: ["old_kongshu"],
    xiahouxuan: ["old_dc_xiahouxuan"],
    tw_zhugejun: ["old_dc_zhugejun"],
    madai: ["old_ol_madai"],
    mb_chenzhi: ["mb_chenzhi", "old_mb_chenzhi"],
    renwan: ["old_renwan"],
    gexuan: ["old_tw_gexuan"],
    xia_zhaoe: ["xia_zhaoe", "old_xia_zhaoe"],
    clan_xunshuang: ["clan_xunshuang", "old_clan_xunshuang"],
    yangxiu: ["old_clan_yangxiu"],
    huangfusong: ["old_wu_huangfusong", "old_jsrg_huangfusong"],
    lukai: ["old_lukai"],
    zhangqiying: ["oldx_zhangqiying"],
    clan_wangmingshan: ["clan_wangmingshan", "old_clan_wangmingshan"],
    guoyuan: ["guoyuan", "old_guoyuan"],
    caocao: ["old_mb_caocao"],
    machao: ["old_v_machao"],
    caochong: ["old_strong_caochong"],
    wufu: ["old_wufu"],
    dc_sb_hulie: ["old_dc_sb_hulie"],
    // re_lusu: ["old_pot_lusu"],
    chengpu: ["old_ol_chengpu"],
    luxun: ["old_dc_sb_luxun"],
    xinxianying: ["old_pot_xinxianying"],
    mengda: ["old_mb_mengda"],
    zhangyan: ["old_mb_zhangyan"],
    dengai: ["old_ol_sb_dengai"],
    ruiji: ["old_ruiji"],
    fuqian: ["old_fuqian"],

    shen_caopi: ["old_shen_caopi"],
    shen_huatuo: ["old_dc_shen_huatuo"],
    //shen_lusu: ["shen_lusu", "old_shen_lusu"],
    shen_guanyu: ["sw_guanyu", "sw_tw_guanyu"],
    shen_lvmeng: ["old_tw_shen_lvmeng", "sw_lvmeng", "sw_tw_lvmeng"],
    shen_zhugeliang: ["sw_zhugeliang", "sw_wechat_zhugelian"],
    shen_zhouyu: ["shen_zhouyu", "sw_zhouyu"],
    shen_simayi: ["old_new_simayi", "sw_simayi"],
    shen_zhaoyun: ["sw_zhaoyun"],
    shen_caocao: ["sw_caocao", "lm_old_caocao"],
    shen_lvbu: ["shen_lvbu", "sw_lvbu"],
    shen_liubei: ["sw_liubei"],
    shen_luxun: ["shen_luxun", "sw_luxun"],
    shen_zhangliao: ["sw_zhangliao"],
    shen_ganning: ["shen_ganning", "sw_ganning"],
    shen_caopi: ["shen_caopi", "sw_caopi"],
    shen_zhenji: ["shen_zhenji", "sw_zhenji"],
    shen_zhangjiao: ["sw_zhangjiao"],
    shen_diaochan: ["shen_diaochan", "sw_diaochan"],
};
export const characterReplace = lmCharacter;